# 🕉️ Fly.io Divine Deployment Configuration
app = "abcsteps-vivek"
primary_region = "sin" # Singapore for Indian users
kill_signal = "SIGINT"
kill_timeout = "30s"

[build]
  dockerfile = "Dockerfile.production"
  
[deploy]
  release_command = "node scripts/release.js"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_NAME = "ABCSteps Vivek Platform"
  # Health check endpoint
  FLY_HEALTH_CHECK = "/api/health"

[experimental]
  auto_rollback = true
  enable_consul = true

# Define app processes
[processes]
  app = "node server.js"
  worker = "node worker.js"

# Persistent storage for uploads
[mounts]
  source = "abcsteps_uploads"
  destination = "/app/uploads"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0