# 🔱 Netlify Sacred Build Configuration
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PLUGIN_NETLIFY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[edge_functions]]
  function = "geolocation"
  path = "/api/location"