# 🕉️ Render.com Deployment Configuration
services:
  # Web Service
  - type: web
    name: abcsteps-vivek
    runtime: node
    region: oregon # or singapore for Asia
    plan: standard # free/starter/standard/pro
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_SITE_NAME
        value: ABCSteps Vivek Learning Platform
      - key: DATABASE_URL
        fromDatabase:
          name: abcsteps-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: abcsteps-redis
          type: redis
          property: connectionString
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false # Set in dashboard
      - key: GOOGLE_CLIENT_ID
        sync: false # Set in dashboard
      - key: GOOGLE_CLIENT_SECRET
        sync: false # Set in dashboard
    autoDeploy: true
    healthCheckPath: /api/health
    numInstances: 2
    domains:
      - abcsteps.onrender.com
      - abcsteps.app
    
  # Background Worker (if needed)
  - type: worker
    name: abcsteps-worker
    runtime: node
    region: oregon
    plan: starter
    buildCommand: pnpm install --frozen-lockfile
    startCommand: node worker.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: abcsteps-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: abcsteps-redis
          type: redis
          property: connectionString

  # Redis Service
  - type: redis
    name: abcsteps-redis
    region: oregon
    plan: starter # free/starter/standard/pro
    maxmemoryPolicy: allkeys-lru

# Database
databases:
  - name: abcsteps-db
    databaseName: abcsteps_vivek
    user: vivek_user
    region: oregon
    plan: starter # free/starter/standard/pro
    postgresMajorVersion: 16